### ISSUE TITLE
The library parses some unicode characters incorrectly

### ISSUE THREAD

**Issue by gaal-dev** [chrisbottin/xml-parser#15]
Hello. It happens here.

`function attribute(): XmlParserAttribute|undefined {
     const m = match(/([\w-:.\u00C0-\u00FF]+)\s*=\s*("[^"]*"|'[^']*'|[\w\u00C0-\u00FF]+)\s*/);
     if (m) {
         return {
             name: m[1],
             value: stripQuotes(m[2])
         };
     }
 }`

This regular expression does not detect some Unicode characters such as ąśćłó (Polish)

const m = match(/([\w-:.\u00C0-\u00FF]+)\s*=\s*("[^"]*"|'[^']*'|[\w\u00C0-\u00FF]+)\s*/);

It is from my test file.

`<?xml version="1.0" encoding="UTF-8" standalone="no" ?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03">
	<CstmrCdtTrfInitn>
		<GrpHdr>
			<MsgId ąśćłó=":">DOMTFR</MsgId>
		</GrpHdr>
		<PmtInf>
			<CdtTrfTxInf>
				<Amt>
					<InstdAmt Ccy="USD">5.00</InstdAmt>
				</Amt>
			</CdtTrfTxInf>
		</PmtInf>
	</CstmrCdtTrfInitn>
</Document>`

The xml-format library was used to format that XML file, but it was corrupted instead.

`
import formatter from "xml-formatter";
...
  beautifyXML = (xml) => {
    try {
      return formatter(xml, {
        indentation: "    ",
        collapseContent: true,
      });
    } catch {
      return xml;
    }
  };
...
`

The created corrupted file.

`<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<Document xmlns="urn:iso:std:iso:20022:tech:xsd:pain.001.001.03">
    <CstmrCdtTrfInitn>
        <GrpHdr>
            <MsgId ó=":" Ccy="USD">
            </MsgId>
            <PmtInf>
                <CdtTrfTxInf>
                    <Amt>
                        <InstdAmt Ccy="USD">5.00</InstdAmt>
                    </Amt>
                </CdtTrfTxInf>
            </PmtInf>
        </GrpHdr>
    </CstmrCdtTrfInitn>
</Document>`

I have investigated what happens.

When the library parses `<MsgId ąśćłó=":">DOMTFR</MsgId>`, it detects the other attribute `<InstdAmt Ccy="USD">5.00</InstdAmt>` and the result is `<MsgId ó=":" Ccy="USD">`

**Comment by chrisbottin** [comment]
Hi @gaal-dev,

Thanks for submitting the issue, yes it appears there is a bug here. I will look into it very soon.

Chris

**Comment by chrisbottin** [comment]
This PR should fix the issue https://github.com/chrisbottin/xml-parser/pull/14

You will need to install version 4.0.2 (https://github.com/chrisbottin/xml-parser/releases/tag/4.0.2)
