### ISSUE TITLE
Build issue

### ISSUE THREAD

**Issue by StephenOsborne0** [chrisbottin/xml-parser#17]
Copying this here for visibility: commit 19d35cf109c58b918576081b15d0dfc503b6dc7b

Getting this error message from the latest commit:
`[commonjs--resolver] Failed to resolve entry for package "xml-parser-xo". The package may have incorrect main/module/exports specified in its package.json`

Maybe due to the relative filepaths on lines 12 specifically? (wild guess)
"main": "./dist/cjs/index.js",

Likewise, if it's a copy/paste error, lines 13-15 may also need updating?
"module": "./dist/esm5/index.js",
  "es2015": "./dist/esm/index.js",
  "types": "./dist/types/index.d.ts",

Kind regards,

**Comment by chrisbottin** [comment]
Should be fixed in version `4.0.4`
